name: Build EssentialsX

on:
  push:
    branches: 
    - 2.x
    - mc/*
  pull_request:
    branches: 
    - 2.x

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Git repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Restore Gradle cache
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: |
        chmod +x gradlew
        ./gradlew build --stacktrace
    - name: Upload Artifacts
      uses: actions/upload-artifact@master
      with:
        name: Plugins Jars
        path: jars/
